language: python
python: 2.7
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=backport
matrix:
  allow_failures:
    - env: TOX_ENV=backport
    - env: TOX_ENV=py34
install:
  - pip install tox
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
  - tox -e $TOX_ENV
