language: python
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.4
      env: TOX_ENV=py34
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: 2.7
      env: TOX_ENV=wheezy
install:
  - pip install -U pip
  - pip install pyflakes tox
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
  - tox -e $TOX_ENV
  - python -m pyflakes.__main__ $(git ls-files | grep -E "^isso/.+.py$" | grep -v "^isso/compat.py")
notifications:
  irc:
    channels:
      - "chat.freenode.net#isso"
    on_success: change
    on_failure: always
