name: E2e tests with docker

on:
  push:
    paths:
      - "./**"
      - "!docs/**"
      - "!.github/**"
      - ".github/workflows/docker-compose.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: |
          docker compose build isso-js-puppeteer-intermediary
          docker compose build isso-server
          docker compose build isso-client

      - name: Bring up containers
        run: docker compose up -d

      - name: Client unit tests
        run: |
          docker run \
          --mount type=bind,source=${{ github.workspace }}/package.json,target=/src/package.json,readonly \
          --mount type=bind,source=${{ github.workspace }}/isso/js/,target=/src/isso/js/,readonly \
          isso-js-testbed npm run test-unit

      - name: Client integration tests
        run: |
          docker run \
          --mount type=bind,source=${{ github.workspace }}/package.json,target=/src/package.json,readonly \
          --mount type=bind,source=${{ github.workspace }}/isso/js/,target=/src/isso/js/,readonly \
          --env ISSO_ENDPOINT='http://isso-dev.local:8080' \
          --network container:isso-server \
          isso-js-testbed npm run test-integration
